"""Canonical backend-neutral ABIs for CaMa-Flood physics kernels."""

from hydroforge.contracts import KernelSpec


_RUNTIME_SCALARS = {
    "gravity": "float32",
    "time_step": "float32",
    "outer_time_step": "float32",
    "adaptive_time_factor": "float32",
    "num_catchments": "index",
    "num_trials": "index",
    "num_sea_level_boundaries": "index",
    "num_bifurcation_paths": "index",
    "num_reservoirs": "index",
    "num_inflow_gauges": "int32",
    "num_levees": "index",
}

_STRUCTURAL_CONSTANTS = {
    "num_bifurcation_levels": "int32",
    "num_flood_levels": "int32",
}


def _spec(
    name,
    parameters,
    size_key,
    *,
    optional=None,
    constants=None,
    optional_values=None,
    read=(),
    write=(),
    read_write=(),
    atomic_add=(),
    atomic_max=(),
    block_sizes=None,
):
    pointer_names = {
        parameter for parameter in parameters if parameter.endswith("_ptr")
    }
    access_groups = {
        "read": set(read),
        "write": set(write),
        "read_write": set(read_write),
        "atomic_add": set(atomic_add),
        "atomic_max": set(atomic_max),
    }
    unknown_access = {
        access: names.difference(pointer_names)
        for access, names in access_groups.items()
        if names.difference(pointer_names)
    }
    if unknown_access:
        raise ValueError(
            f"{name}: buffer access names are not pointer arguments: {unknown_access}"
        )
    claimed = {}
    for access, names in access_groups.items():
        for parameter in names:
            previous = claimed.setdefault(parameter, access)
            if previous != access:
                raise ValueError(
                    f"{name}: pointer {parameter!r} has conflicting access "
                    f"{previous!r} and {access!r}"
                )
    missing_access = pointer_names.difference(claimed)
    if missing_access:
        raise ValueError(
            f"{name}: every pointer requires one explicit access mode; "
            f"missing={sorted(missing_access)}"
        )
    buffers = {parameter: claimed[parameter] for parameter in pointer_names}
    constants = dict(constants or {})
    constants.update(
        {
            parameter: _STRUCTURAL_CONSTANTS[parameter]
            for parameter in parameters
            if parameter in _STRUCTURAL_CONSTANTS
        }
    )
    scalar_names = set(parameters).difference(buffers, constants)
    unknown_scalars = scalar_names.difference(_RUNTIME_SCALARS)
    if unknown_scalars:
        raise ValueError(f"{name}: undefined runtime scalar kind(s): {unknown_scalars}")
    return KernelSpec(
        name=name,
        parameters=parameters,
        size_key=size_key,
        buffers=buffers,
        optional_buffers=optional or {},
        compile_time=constants,
        runtime_scalars={
            parameter: _RUNTIME_SCALARS[parameter] for parameter in scalar_names
        },
        optional_values=optional_values or {},
        block_sizes=block_sizes or {},
    )


OUTFLOW = _spec(
    "compute_outflow",
    (
        "downstream_idx_ptr",
        "river_inflow_ptr",
        "river_outflow_ptr",
        "river_manning_ptr",
        "river_depth_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "river_height_ptr",
        "river_storage_ptr",
        "flood_inflow_ptr",
        "flood_outflow_ptr",
        "flood_manning_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "is_levee_ptr",
        "catchment_elevation_ptr",
        "downstream_distance_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
        "river_cross_section_depth_ptr",
        "flood_cross_section_depth_ptr",
        "flood_cross_section_area_ptr",
        "global_bifurcation_outflow_ptr",
        "total_storage_ptr",
        "outgoing_storage_ptr",
        "water_surface_elevation_ptr",
        "protected_water_surface_elevation_ptr",
        "gravity",
        "time_step_ptr",
        "num_catchments",
        "HAS_BIFURCATION",
        "HAS_TOTAL_STORAGE",
        "HAS_WATER_SURFACE",
        "HAS_PROTECTED_WATER_SURFACE",
        "HAS_LEVEE",
        "is_dam_upstream_ptr",
        "HAS_RESERVOIR",
        "MIN_KINEMATIC_SLOPE",
        "sea_surface_elevation_ptr",
        "catchment_sea_level_idx_ptr",
        "HAS_SEA_LEVEL",
        "num_trials",
        "batched_river_manning",
        "batched_flood_manning",
        "batched_river_width",
        "batched_river_length",
        "batched_river_height",
        "batched_catchment_elevation",
        "batched_downstream_distance",
        "batched_sea_surface_elevation",
        "num_sea_level_boundaries",
    ),
    "num_catchments",
    optional={
        "global_bifurcation_outflow_ptr": "HAS_BIFURCATION",
        "total_storage_ptr": None,
        "water_surface_elevation_ptr": None,
        "protected_water_surface_elevation_ptr": None,
        "is_levee_ptr": "HAS_LEVEE",
        "is_dam_upstream_ptr": "HAS_RESERVOIR",
        "sea_surface_elevation_ptr": "HAS_SEA_LEVEL",
        "catchment_sea_level_idx_ptr": "HAS_SEA_LEVEL",
    },
    constants={
        "HAS_BIFURCATION": "bool",
        "HAS_TOTAL_STORAGE": "bool",
        "HAS_WATER_SURFACE": "bool",
        "HAS_PROTECTED_WATER_SURFACE": "bool",
        "HAS_LEVEE": "bool",
        "HAS_RESERVOIR": "bool",
        "MIN_KINEMATIC_SLOPE": "float32",
        "HAS_SEA_LEVEL": "bool",
        "batched_river_manning": "bool",
        "batched_flood_manning": "bool",
        "batched_river_width": "bool",
        "batched_river_length": "bool",
        "batched_sea_surface_elevation": "bool",
        "batched_river_height": "bool",
        "batched_catchment_elevation": "bool",
        "batched_downstream_distance": "bool",
    },
    optional_values={"num_sea_level_boundaries": ("HAS_SEA_LEVEL", 0)},
    read=(
        "downstream_idx_ptr",
        "river_manning_ptr",
        "river_depth_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "river_height_ptr",
        "river_storage_ptr",
        "flood_manning_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "is_levee_ptr",
        "catchment_elevation_ptr",
        "downstream_distance_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
        "time_step_ptr",
        "is_dam_upstream_ptr",
        "sea_surface_elevation_ptr",
        "catchment_sea_level_idx_ptr",
    ),
    write=(
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "global_bifurcation_outflow_ptr",
        "total_storage_ptr",
        "water_surface_elevation_ptr",
        "protected_water_surface_elevation_ptr",
    ),
    read_write=(
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "river_cross_section_depth_ptr",
        "flood_cross_section_depth_ptr",
        "flood_cross_section_area_ptr",
    ),
    atomic_add=("outgoing_storage_ptr",),
)

INFLOW = _spec(
    "compute_inflow",
    (
        "downstream_idx_ptr",
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "outgoing_storage_ptr",
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "limit_rate_ptr",
        "reservoir_total_inflow_ptr",
        "is_reservoir_ptr",
        "num_catchments",
        "HAS_BIFURCATION",
        "HAS_RESERVOIR",
        "num_trials",
    ),
    "num_catchments",
    optional={
        "limit_rate_ptr": "HAS_BIFURCATION",
        "reservoir_total_inflow_ptr": "HAS_RESERVOIR",
        "is_reservoir_ptr": "HAS_RESERVOIR",
    },
    constants={"HAS_BIFURCATION": "bool", "HAS_RESERVOIR": "bool"},
    read=(
        "downstream_idx_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "outgoing_storage_ptr",
        "is_reservoir_ptr",
    ),
    write=("limit_rate_ptr",),
    read_write=("river_outflow_ptr", "flood_outflow_ptr"),
    atomic_add=(
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "reservoir_total_inflow_ptr",
    ),
)

ADAPTIVE_TIME = _spec(
    "compute_adaptive_time_step",
    (
        "river_depth_ptr",
        "downstream_distance_ptr",
        "is_dam_related_ptr",
        "max_sub_steps_ptr",
        "outer_time_step",
        "adaptive_time_factor",
        "gravity",
        "num_catchments",
        "HAS_RESERVOIR",
        "num_trials",
        "batched_downstream_distance",
    ),
    "num_catchments",
    optional={"is_dam_related_ptr": "HAS_RESERVOIR"},
    constants={"HAS_RESERVOIR": "bool", "batched_downstream_distance": "bool"},
    read=(
        "river_depth_ptr",
        "downstream_distance_ptr",
        "is_dam_related_ptr",
    ),
    atomic_max=("max_sub_steps_ptr",),
    block_sizes={"metal": 256},
)

BIFURCATION_OUTFLOW = _spec(
    "compute_bifurcation_outflow",
    (
        "bifurcation_catchment_idx_ptr",
        "bifurcation_downstream_idx_ptr",
        "bifurcation_manning_ptr",
        "bifurcation_outflow_ptr",
        "bifurcation_width_ptr",
        "bifurcation_length_ptr",
        "bifurcation_elevation_ptr",
        "bifurcation_cross_section_depth_ptr",
        "water_surface_elevation_ptr",
        "total_storage_ptr",
        "outgoing_storage_ptr",
        "gravity",
        "time_step_ptr",
        "num_bifurcation_paths",
        "num_bifurcation_levels",
        "num_trials",
        "num_catchments",
        "batched_bifurcation_manning",
        "batched_bifurcation_width",
        "batched_bifurcation_length",
        "batched_bifurcation_elevation",
    ),
    "num_bifurcation_paths",
    constants={
        "batched_bifurcation_manning": "bool",
        "batched_bifurcation_width": "bool",
        "batched_bifurcation_length": "bool",
        "batched_bifurcation_elevation": "bool",
    },
    read=(
        "bifurcation_catchment_idx_ptr",
        "bifurcation_downstream_idx_ptr",
        "bifurcation_manning_ptr",
        "bifurcation_width_ptr",
        "bifurcation_length_ptr",
        "bifurcation_elevation_ptr",
        "water_surface_elevation_ptr",
        "total_storage_ptr",
        "time_step_ptr",
    ),
    read_write=(
        "bifurcation_outflow_ptr",
        "bifurcation_cross_section_depth_ptr",
    ),
    atomic_add=("outgoing_storage_ptr",),
)

BIFURCATION_INFLOW = _spec(
    "compute_bifurcation_inflow",
    (
        "bifurcation_catchment_idx_ptr",
        "bifurcation_downstream_idx_ptr",
        "limit_rate_ptr",
        "bifurcation_outflow_ptr",
        "global_bifurcation_outflow_ptr",
        "num_bifurcation_paths",
        "num_bifurcation_levels",
        "num_trials",
        "num_catchments",
    ),
    "num_bifurcation_paths",
    read=(
        "bifurcation_catchment_idx_ptr",
        "bifurcation_downstream_idx_ptr",
        "limit_rate_ptr",
    ),
    read_write=("bifurcation_outflow_ptr",),
    atomic_add=("global_bifurcation_outflow_ptr",),
)

RESERVOIR_OUTFLOW = _spec(
    "compute_reservoir_outflow",
    (
        "reservoir_catchment_idx_ptr",
        "downstream_idx_ptr",
        "reservoir_total_inflow_ptr",
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "conservation_volume_ptr",
        "emergency_volume_ptr",
        "adjustment_volume_ptr",
        "effective_normal_outflow_ptr",
        "adjustment_outflow_ptr",
        "flood_control_outflow_ptr",
        "runoff_ptr",
        "total_storage_ptr",
        "outgoing_storage_ptr",
        "time_step_ptr",
        "num_reservoirs",
        "num_catchments",
        "num_trials",
        "batched_runoff",
    ),
    "num_reservoirs",
    constants={"batched_runoff": "bool"},
    read=(
        "reservoir_catchment_idx_ptr",
        "downstream_idx_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "conservation_volume_ptr",
        "emergency_volume_ptr",
        "adjustment_volume_ptr",
        "effective_normal_outflow_ptr",
        "adjustment_outflow_ptr",
        "flood_control_outflow_ptr",
        "runoff_ptr",
        "time_step_ptr",
    ),
    write=("total_storage_ptr",),
    read_write=(
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "reservoir_total_inflow_ptr",
    ),
    atomic_add=("outgoing_storage_ptr",),
)

FLOOD_STAGE = _spec(
    "compute_flood_stage",
    (
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "global_bifurcation_outflow_ptr",
        "runoff_ptr",
        "inflow_ptr",
        "catchment_inflow_idx_ptr",
        "time_step_ptr",
        "outgoing_storage_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "flood_fraction_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "num_catchments",
        "num_flood_levels",
        "HAS_BIFURCATION",
        "HAS_INFLOW",
        "num_trials",
        "batched_runoff",
        "batched_inflow",
        "batched_river_height",
        "batched_flood_depth_table",
        "batched_catchment_area",
        "batched_river_width",
        "batched_river_length",
        "num_inflow_gauges",
    ),
    "num_catchments",
    optional={
        "global_bifurcation_outflow_ptr": "HAS_BIFURCATION",
        "inflow_ptr": "HAS_INFLOW",
        "catchment_inflow_idx_ptr": "HAS_INFLOW",
    },
    constants={
        "HAS_BIFURCATION": "bool",
        "HAS_INFLOW": "bool",
        "batched_runoff": "bool",
        "batched_inflow": "bool",
        "batched_river_height": "bool",
        "batched_flood_depth_table": "bool",
        "batched_catchment_area": "bool",
        "batched_river_width": "bool",
        "batched_river_length": "bool",
    },
    optional_values={"num_inflow_gauges": ("HAS_INFLOW", 0)},
    read=(
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "global_bifurcation_outflow_ptr",
        "runoff_ptr",
        "inflow_ptr",
        "catchment_inflow_idx_ptr",
        "time_step_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
    ),
    write=(
        "outgoing_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "flood_fraction_ptr",
    ),
    read_write=(
        "river_storage_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
    ),
)

FLOOD_STAGE_LOG = _spec(
    "compute_flood_stage_log",
    (
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "global_bifurcation_outflow_ptr",
        "runoff_ptr",
        "inflow_ptr",
        "catchment_inflow_idx_ptr",
        "time_step_ptr",
        "outgoing_storage_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "flood_fraction_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "is_levee_ptr",
        "total_storage_pre_sum_ptr",
        "total_storage_next_sum_ptr",
        "total_storage_new_sum_ptr",
        "total_inflow_sum_ptr",
        "total_outflow_sum_ptr",
        "total_storage_stage_sum_ptr",
        "river_storage_sum_ptr",
        "flood_storage_sum_ptr",
        "flood_area_sum_ptr",
        "total_inflow_error_sum_ptr",
        "total_stage_error_sum_ptr",
        "current_step_ptr",
        "num_catchments",
        "num_flood_levels",
        "HAS_BIFURCATION",
        "HAS_INFLOW",
        "HAS_LEVEE",
    ),
    "num_catchments",
    optional={
        "global_bifurcation_outflow_ptr": "HAS_BIFURCATION",
        "inflow_ptr": "HAS_INFLOW",
        "catchment_inflow_idx_ptr": "HAS_INFLOW",
        "is_levee_ptr": "HAS_LEVEE",
    },
    constants={"HAS_BIFURCATION": "bool", "HAS_INFLOW": "bool", "HAS_LEVEE": "bool"},
    read=(
        "river_inflow_ptr",
        "flood_inflow_ptr",
        "river_outflow_ptr",
        "flood_outflow_ptr",
        "global_bifurcation_outflow_ptr",
        "runoff_ptr",
        "inflow_ptr",
        "catchment_inflow_idx_ptr",
        "time_step_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "is_levee_ptr",
        "current_step_ptr",
    ),
    write=(
        "outgoing_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "flood_fraction_ptr",
    ),
    read_write=(
        "river_storage_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
    ),
    atomic_add=(
        "total_storage_pre_sum_ptr",
        "total_storage_next_sum_ptr",
        "total_storage_new_sum_ptr",
        "total_inflow_sum_ptr",
        "total_outflow_sum_ptr",
        "total_storage_stage_sum_ptr",
        "river_storage_sum_ptr",
        "flood_storage_sum_ptr",
        "flood_area_sum_ptr",
        "total_inflow_error_sum_ptr",
        "total_stage_error_sum_ptr",
    ),
    # The Metal body folds the water-balance counters through threadgroup
    # memory, which needs a compile-time threadgroup width.
    block_sizes={"metal": 256},
)

LEVEE_STAGE = _spec(
    "compute_levee_stage",
    (
        "levee_catchment_idx_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "levee_base_height_ptr",
        "levee_crown_height_ptr",
        "levee_fraction_ptr",
        "flood_fraction_ptr",
        "num_levees",
        "num_flood_levels",
        "num_trials",
        "num_catchments",
        "batched_river_length",
        "batched_river_width",
        "batched_river_height",
        "batched_catchment_area",
        "batched_levee_crown_height",
        "batched_levee_fraction",
        "batched_levee_base_height",
        "batched_flood_depth_table",
    ),
    "num_levees",
    constants={
        "batched_river_length": "bool",
        "batched_river_width": "bool",
        "batched_river_height": "bool",
        "batched_catchment_area": "bool",
        "batched_levee_crown_height": "bool",
        "batched_levee_fraction": "bool",
        "batched_levee_base_height": "bool",
        "batched_flood_depth_table": "bool",
    },
    read=(
        "levee_catchment_idx_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "levee_base_height_ptr",
        "levee_crown_height_ptr",
        "levee_fraction_ptr",
    ),
    write=("protected_storage_ptr", "protected_depth_ptr"),
    read_write=(
        "river_storage_ptr",
        "flood_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "flood_fraction_ptr",
    ),
)

LEVEE_STAGE_LOG = _spec(
    "compute_levee_stage_log",
    (
        "levee_catchment_idx_ptr",
        "river_storage_ptr",
        "flood_storage_ptr",
        "protected_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "protected_depth_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "levee_base_height_ptr",
        "levee_crown_height_ptr",
        "levee_fraction_ptr",
        "flood_fraction_ptr",
        "total_storage_stage_sum_ptr",
        "river_storage_sum_ptr",
        "flood_storage_sum_ptr",
        "flood_area_sum_ptr",
        "total_stage_error_sum_ptr",
        "current_step_ptr",
        "num_levees",
        "num_flood_levels",
    ),
    "num_levees",
    read=(
        "levee_catchment_idx_ptr",
        "river_height_ptr",
        "flood_depth_table_ptr",
        "catchment_area_ptr",
        "river_width_ptr",
        "river_length_ptr",
        "levee_base_height_ptr",
        "levee_crown_height_ptr",
        "levee_fraction_ptr",
        "current_step_ptr",
    ),
    write=("protected_storage_ptr", "protected_depth_ptr"),
    read_write=(
        "river_storage_ptr",
        "flood_storage_ptr",
        "river_depth_ptr",
        "flood_depth_ptr",
        "flood_fraction_ptr",
    ),
    atomic_add=(
        "total_storage_stage_sum_ptr",
        "river_storage_sum_ptr",
        "flood_storage_sum_ptr",
        "flood_area_sum_ptr",
        "total_stage_error_sum_ptr",
    ),
    # The Metal body folds the water-balance counters through threadgroup
    # memory, which needs a compile-time threadgroup width.
    block_sizes={"metal": 256},
)

LEVEE_BIFURCATION_OUTFLOW = _spec(
    "compute_levee_bifurcation_outflow",
    (
        "bifurcation_catchment_idx_ptr",
        "bifurcation_downstream_idx_ptr",
        "bifurcation_manning_ptr",
        "bifurcation_outflow_ptr",
        "bifurcation_width_ptr",
        "bifurcation_length_ptr",
        "bifurcation_elevation_ptr",
        "bifurcation_cross_section_depth_ptr",
        "water_surface_elevation_ptr",
        "protected_water_surface_elevation_ptr",
        "total_storage_ptr",
        "outgoing_storage_ptr",
        "gravity",
        "time_step_ptr",
        "num_bifurcation_paths",
        "num_bifurcation_levels",
        "num_trials",
        "num_catchments",
        "batched_bifurcation_manning",
        "batched_bifurcation_width",
        "batched_bifurcation_length",
        "batched_bifurcation_elevation",
    ),
    "num_bifurcation_paths",
    constants={
        "batched_bifurcation_manning": "bool",
        "batched_bifurcation_width": "bool",
        "batched_bifurcation_length": "bool",
        "batched_bifurcation_elevation": "bool",
    },
    read=(
        "bifurcation_catchment_idx_ptr",
        "bifurcation_downstream_idx_ptr",
        "bifurcation_manning_ptr",
        "bifurcation_width_ptr",
        "bifurcation_length_ptr",
        "bifurcation_elevation_ptr",
        "water_surface_elevation_ptr",
        "protected_water_surface_elevation_ptr",
        "total_storage_ptr",
        "time_step_ptr",
    ),
    read_write=(
        "bifurcation_outflow_ptr",
        "bifurcation_cross_section_depth_ptr",
    ),
    atomic_add=("outgoing_storage_ptr",),
)
