[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
name = "cmfgpu"
version = "0.1"
description = ""
authors = [
    {name = "Shengyu Kang", email = "kshy0204@whu.edu.cn"}
]
dependencies = [
    "hydroforge>=0.3.0",
    "netCDF4",
    "scipy",
    "numba",
    "pydantic",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cmfgpu*"]

[tool.setuptools.package-data]
"cmfgpu.phys.cuda" = ["*.cu", "*.cuh"]
"cmfgpu.phys.metal" = ["*.metal"]

[project.optional-dependencies]
dev = ["ipykernel", "matplotlib", "ipympl", "pandas", "meson", "ninja"]

[tool.ruff]
target-version = "py311"
extend-exclude = ["inp", "out", "private"]

[tool.ruff.lint]
select = ["UP006", "UP007", "UP035", "UP045"]
