# LICENSE HEADER MANAGED BY add-license-header
# Copyright (c) 2025 Shengyu Kang (Wuhan University)
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#

"""
Base module for CaMa-Flood-GPU using the TensorField / computed_tensor_field
helpers for concise tensor metadata.
"""
from __future__ import annotations

from functools import cached_property
from typing import ClassVar, List, Literal, Optional, Self, Tuple

import torch
from hydroforge.model.module import (AbstractModule, CoordinateField,
                                        ReferenceField, ReferenceIndexField,
                                        SelectionField, TensorField,
                                        computed_tensor_field)
from pydantic import Field, computed_field, model_validator


def BaseField(
    description: str,
    shape: Tuple[str, ...] = ("num_catchments",),
    dtype: Literal["float", "int", "idx", "bool", "hpfloat"] = "float",
    dim_coords: Optional[str] = "catchment_id",
    category: Literal["topology", "param", "init_state", "state"] = "param",
    mode: Literal["device", "cpu", "discard"] = "device",
    **kwargs
):

    return TensorField(
        description=description,
        shape=shape,
        dtype=dtype,
        dim_coords=dim_coords,
        category=category,
        mode=mode,
        **kwargs
    )

def computed_base_field(
    description: str,
    shape: Tuple[str, ...] = ("num_catchments",),
    dtype: Literal["float", "int", "idx", "bool", "hpfloat"] = "float",
    dim_coords: Optional[str] = "catchment_id",
    category: Literal["topology", "derived_param", "state", "virtual"] = "derived_param",
    expr: Optional[str] = None,
    depends_on: Optional[str] = None,
    **kwargs
):
    return computed_tensor_field(
        description=description,
        shape=shape,
        dtype=dtype,
        dim_coords=dim_coords,
        category=category,
        expr=expr,
        depends_on=depends_on,
        **kwargs
    )

class BaseModule(AbstractModule):
    # --------------------------------------------------------------------- #
    # Metadata
    # --------------------------------------------------------------------- #
    module_name: ClassVar[str] = "base"
    description: ClassVar[str] = (
        "Core hydrodynamic module with fundamental river and catchment variables"
    )
    dependencies: ClassVar[List[str]] = []

    # --------------------------------------------------------------------- #
    # Scalars (dimensions & constants)
    # --------------------------------------------------------------------- #
    gravity: float = Field(
        default=9.8,
        description="Gravitational acceleration constant (m/s²)",
        gt=0.0,
        allow_inf_nan=False,
    )
    min_kinematic_slope: float = Field(
        default=1.0e-5,
        description="Minimum bed slope for kinematic wave",
        gt=0.0,
        allow_inf_nan=False,
    )

    # --------------------------------------------------------------------- #
    # Network topology
    # --------------------------------------------------------------------- #
    catchment_id: torch.Tensor = CoordinateField(
        description=(
            "Unique ID of each catchment (e.g., generated by "
            "catchment_id = np.ravel_multi_index((catchment_x, catchment_y), self.map_shape))"
        ),
        dtype="int",
        shape=("num_catchments",),
    )

    catchment_basin_id: torch.Tensor = BaseField(
        description="Basin identifier for distributed sharding",
        dtype="int",
        category="topology",
        mode="cpu",
    )


    downstream_id: torch.Tensor = ReferenceField(
        description="ID of immediate downstream catchment (points to self at river mouth)",
        dtype="int",
        shape=("num_catchments",),
        dim_coords="catchment_id",
        references="catchment_id",
    )

    # --------------------------------------------------------------------- #
    # River-channel geometry
    # --------------------------------------------------------------------- #
    river_width: torch.Tensor = BaseField(
        description="River-channel width (m)",
        category="param",
        shape=("num_catchments",),
    )

    river_length: torch.Tensor = BaseField(
        description="River-channel length (m)",
        category="param",
        shape=("num_catchments",),
    )

    river_height: torch.Tensor = BaseField(
        description="Bankfull depth of river channel (m)",
        category="param",
        shape=("num_catchments",),
    )

    # --------------------------------------------------------------------- #
    # Catchment properties
    # --------------------------------------------------------------------- #
    catchment_elevation: torch.Tensor = BaseField(
        description="Mean ground elevation (m a.s.l.)",
        category="param",
    )

    catchment_area: torch.Tensor = BaseField(
        description="Surface area of catchment (m²)",
        category="param",
    )

    runoff: torch.Tensor = BaseField(
        description="Current external runoff forcing (m³/s)",
        category="state",
        output="disabled",
        default=0,
    )

    downstream_distance: torch.Tensor = BaseField(
        description="Downstream distance (m)",
        category="param",
    )

    output_catchment_id: torch.Tensor = SelectionField(
        description="Catchment IDs for which output will be saved.",
        dtype="int",
        shape=("num_output_catchments",),
        selects="catchment_id",
    )

    # --------------------------------------------------------------------- #
    # hydrodynamic parameters
    # --------------------------------------------------------------------- #
    river_manning: torch.Tensor = BaseField(
        description="Manning roughness for rivers (-)",
        default=0.03,
        category="param",
    )

    flood_manning: torch.Tensor = BaseField(
        description="Manning roughness for floodplains (-)",
        default=0.1,
        category="param",
    )

    # --------------------------------------------------------------------- #
    # Lookup tables (dependent on num_flood_levels)
    # --------------------------------------------------------------------- #
    flood_depth_table: torch.Tensor = BaseField(
        description="Lookup table: flood depth vs. fraction of catchment area flooded (m)",
        shape=("num_catchments", "num_flood_levels"),
        category="param",
    )

    # --------------------------------------------------------------------- #
    # State variables (initialised to 0 where not supplied)
    # --------------------------------------------------------------------- #
    river_storage: torch.Tensor = BaseField(
        description="Current water volume in river channels, including any above bankfull depth (m³).",
        default=0,
        category="init_state",
        dtype="hpfloat",
    )

    flood_storage: torch.Tensor = BaseField(
        description="Current water volume stored on floodplains (m³)",
        default=0,
        category="init_state",
        dtype="hpfloat",
    )

    protected_storage: torch.Tensor = BaseField(
        description="Current water volume stored in protected areas (m³)",
        default=0,
        category="init_state",
        dtype="hpfloat",
    )

    protected_depth: torch.Tensor = BaseField(
        description="Current water depth on the protected side relative to river bed (m)",
        default=0,
        category="init_state",
    )
    
    river_depth: torch.Tensor = BaseField(
        description="Current water depth in rivers (m)",
        default=0,
        category="init_state",
    )

    flood_depth: torch.Tensor = BaseField(
        description="Current water depth on floodplains above river bankfull (m)",
        default=0,
        category="init_state",
    )

    river_outflow: torch.Tensor = BaseField(
        description="Volumetric flow rate out of rivers (m³ s⁻¹)",
        default=0,
        category="init_state",
    )

    flood_outflow: torch.Tensor = BaseField(
        description="Volumetric flow rate out of floodplains (m³ s⁻¹)",
        default=0,
        category="init_state",
    )

    river_cross_section_depth: torch.Tensor = BaseField(
        description="Effective water depth used in river-flow calculations (m)",
        default=0,
        category="init_state",
    )

    flood_cross_section_depth: torch.Tensor = BaseField(
        description="Effective water depth used in flood-flow calculations (m)",
        default=0,
        category="init_state",
    )

    flood_cross_section_area: torch.Tensor = BaseField(
        description="Cross-sectional flow area on floodplains (m²)",
        default=0,
        category="init_state",
    )

    # ------------------------------------------------------------------ #
    # Computed scalar dimensions
    # ------------------------------------------------------------------ #
    @computed_field(
        description="Total number of catchments."
    )
    @cached_property
    def num_catchments(self) -> int:
        return self.catchment_id.shape[0]

    @computed_field(
        description="Number of catchments that will have their output saved."
    )
    @cached_property
    def num_output_catchments(self) -> int:
        return self.output_catchment_id.shape[0]
    
    @computed_field(
        description="Number of flood levels represented in the lookup tables."
    )
    @cached_property
    def num_flood_levels(self) -> int:
        return self.flood_depth_table.shape[-1]

    # ------------------------------------------------------------------ #
    # Computed tensor fields
    # ------------------------------------------------------------------ #
    downstream_idx = ReferenceIndexField("downstream_id")

    @computed_base_field(
        description="Total water storage per catchment (m³)",
        category="state",
        dtype="hpfloat",
        required_by=("bifurcation", "reservoir"),
        output="disabled",
    )
    @cached_property
    def total_storage(self) -> Optional[torch.Tensor]:
        if not {"bifurcation", "reservoir"}.intersection(
            self.opened_modules,
        ):
            return None
        return self.river_storage + self.flood_storage + self.protected_storage

    # ---------------- Hidden / intermediate states ------------------- #
    @computed_base_field(
        description=("Total outgoing storage from each catchment (m³)"
                     "Can not be saved, as it is a temporary state."),
        output="disabled",
        category="state",
        dtype="hpfloat",
    )
    @cached_property
    def outgoing_storage(self) -> torch.Tensor:
        return torch.zeros_like(self.river_outflow, dtype=self.high_precision)

    @computed_base_field(
        description="Water-surface elevation (m a.s.l.)",
        category="state",
        depends_on="bifurcation",
        output="disabled",
    )
    @cached_property
    def water_surface_elevation(self) -> Optional[torch.Tensor]:
        if "bifurcation" not in self.opened_modules:
            return None
        return torch.zeros_like(self.river_outflow)

    @computed_base_field(
        description="Protected water-surface elevation (m a.s.l.)",
        category="state",
        depends_on=("bifurcation", "levee"),
        output="disabled",
    )
    @cached_property
    def protected_water_surface_elevation(self) -> Optional[torch.Tensor]:
        if not {"bifurcation", "levee"}.issubset(self.opened_modules):
            return None
        return torch.zeros_like(self.river_outflow)

    @computed_base_field(
        description="Total inflow into river channels (m³ s⁻¹)",
        category="state",
        dtype="hpfloat",
    )
    @cached_property
    def river_inflow(self) -> torch.Tensor:
        return torch.zeros_like(self.river_outflow, dtype=self.high_precision)

    @computed_base_field(
        description="Total flooded area (m²)",
        category="virtual",
        expr="flood_fraction * catchment_area"
    )
    @cached_property
    def flood_area(self) -> Optional[torch.Tensor]:
        return None

    @computed_base_field(
        description="Fraction of catchment area that is flooded (-)",
        category="state",
    )
    @cached_property
    def flood_fraction(self) -> torch.Tensor:
        return torch.zeros_like(self.river_outflow)

    @computed_base_field(
        description="Total inflow to floodplains (m³ s⁻¹)",
        category="state",
        dtype="hpfloat",
    )
    @cached_property
    def flood_inflow(self) -> torch.Tensor:
        return torch.zeros_like(self.river_outflow, dtype=self.high_precision)

    @computed_base_field(
        description="Total outflow from catchment (river + flood) (m³ s⁻¹)",
        category="virtual",
        expr="river_outflow + flood_outflow",
    )
    @cached_property
    def total_outflow(self) -> Optional[torch.Tensor]:
        return None

    # ------------------------------------------------------------------ #
    # Mutable scalar buffers (1-element device tensors for CUDA Graph)
    # ------------------------------------------------------------------ #
    @computed_base_field(
        description="Current sub-step time step (seconds). "
                    "Updated via .fill_() before each sub-step loop.",
        shape=(1,),
        output="disabled",
        category="shared_state",
    )
    @cached_property
    def time_step(self) -> torch.Tensor:
        return torch.zeros(1, dtype=self.precision, device=self.device)

    @computed_base_field(
        description="Current sub-step index within the time step. "
                    "Updated via .fill_() before each sub-step for log kernels.",
        shape=(1,),
        output="disabled",
        category="shared_state",
        dtype="idx",
    )
    @cached_property
    def current_step(self) -> torch.Tensor:
        return torch.zeros(1, dtype=torch.int32, device=self.device)



    # ------------------------------------------------------------------ #
    # Post-init validation
    # ------------------------------------------------------------------ #
    @model_validator(mode="after")
    def validate_physical_parameters(self) -> Self:
        strictly_positive = {
            "river_width": self.river_width,
            "river_length": self.river_length,
            "river_height": self.river_height,
            "catchment_area": self.catchment_area,
            "downstream_distance": self.downstream_distance,
            "river_manning": self.river_manning,
            "flood_manning": self.flood_manning,
        }
        invalid_counts = {
            name: int((~torch.isfinite(value) | (value <= 0)).sum().item())
            for name, value in strictly_positive.items()
        }
        invalid_counts = {
            name: count for name, count in invalid_counts.items() if count
        }
        if invalid_counts:
            details = ", ".join(
                f"{name}={count}" for name, count in invalid_counts.items()
            )
            raise ValueError(
                "River geometry, catchment area, downstream distance, and "
                "Manning coefficients must contain only finite values greater "
                f"than zero; invalid element counts: {details}"
            )

        finite_only = {
            "catchment_elevation": self.catchment_elevation,
            "flood_depth_table": self.flood_depth_table,
        }
        nonfinite_counts = {
            name: int((~torch.isfinite(value)).sum().item())
            for name, value in finite_only.items()
        }
        nonfinite_counts = {
            name: count for name, count in nonfinite_counts.items() if count
        }
        if nonfinite_counts:
            details = ", ".join(
                f"{name}={count}" for name, count in nonfinite_counts.items()
            )
            raise ValueError(
                "Elevation and flood-depth lookup values must be finite; "
                f"invalid element counts: {details}"
            )
        negative_depths = int((self.flood_depth_table < 0).sum().item())
        if negative_depths:
            raise ValueError(
                "flood_depth_table must be non-negative; "
                f"invalid element count: {negative_depths}"
            )

        nonnegative_state = {
            "river_storage": self.river_storage,
            "flood_storage": self.flood_storage,
            "protected_storage": self.protected_storage,
            "protected_depth": self.protected_depth,
            "river_depth": self.river_depth,
            "flood_depth": self.flood_depth,
            "river_cross_section_depth": self.river_cross_section_depth,
            "flood_cross_section_depth": self.flood_cross_section_depth,
            "flood_cross_section_area": self.flood_cross_section_area,
        }
        invalid_state_counts = {
            name: int((~torch.isfinite(value) | (value < 0)).sum().item())
            for name, value in nonnegative_state.items()
        }
        invalid_state_counts = {
            name: count
            for name, count in invalid_state_counts.items()
            if count
        }
        if invalid_state_counts:
            details = ", ".join(
                f"{name}={count}"
                for name, count in invalid_state_counts.items()
            )
            raise ValueError(
                "Initial storage, depth, and cross-section state must contain "
                "only finite non-negative values; invalid element counts: "
                f"{details}"
            )

        nonfinite_flow_counts = {
            name: int((~torch.isfinite(value)).sum().item())
            for name, value in {
                "river_outflow": self.river_outflow,
                "flood_outflow": self.flood_outflow,
            }.items()
        }
        nonfinite_flow_counts = {
            name: count
            for name, count in nonfinite_flow_counts.items()
            if count
        }
        if nonfinite_flow_counts:
            details = ", ".join(
                f"{name}={count}"
                for name, count in nonfinite_flow_counts.items()
            )
            raise ValueError(
                "Initial river and flood outflow must contain only finite "
                f"values; invalid element counts: {details}"
            )
        return self

    @model_validator(mode="after")
    def validate_flood_depth_table_monotonicity(self) -> Self:
        if self.num_flood_levels > 1:
            diffs = torch.diff(self.flood_depth_table, dim=-1)
            invalid = diffs < 0
            num_invalid = int(invalid.sum().item())
            if num_invalid:
                min_diff = diffs.min().item()
                raise ValueError(
                    "flood_depth_table must be monotonically non-decreasing; "
                    f"found {num_invalid} decreasing intervals "
                    f"(minimum diff={min_diff:.6f}). Regenerate the parameter "
                    "file with MERITMap."
                )
        return self
