# LICENSE HEADER MANAGED BY add-license-header
# Copyright (c) 2025 Shengyu Kang (Wuhan University)
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#

"""
Base module for CaMa-Flood-GPU using the TensorField / computed_tensor_field
helpers for concise tensor metadata.
"""

from __future__ import annotations

from functools import cached_property
from typing import ClassVar, Literal, Self

import torch
from hydroforge.model import (
    AbstractModule,
    CoordinateField,
    ReferenceField,
    ReferenceIndexField,
    SelectionField,
    TensorField,
    computed_tensor_field,
    kernel_field,
)
from pydantic import computed_field, model_validator


def BaseField(
    description: str,
    shape: tuple[str, ...] = ("num_catchments",),
    dtype: Literal["float", "int", "idx", "bool", "hpfloat"] = "float",
    dim_coords: str | None = "catchment_id",
    category: Literal["topology", "param", "forcing", "init_state", "state"] = "param",
    mode: Literal["device", "cpu", "discard"] = "device",
    **kwargs,
):

    return TensorField(
        description=description,
        shape=shape,
        dtype=dtype,
        dim_coords=dim_coords,
        category=category,
        mode=mode,
        **kwargs,
    )


def computed_base_field(
    description: str,
    shape: tuple[str, ...] = ("num_catchments",),
    dtype: Literal["float", "int", "idx", "bool", "hpfloat"] = "float",
    dim_coords: str | None = "catchment_id",
    category: Literal[
        "topology", "derived_param", "state", "virtual"
    ] = "derived_param",
    expr: str | None = None,
    depends_on: str | None = None,
    **kwargs,
):
    return computed_tensor_field(
        description=description,
        shape=shape,
        dtype=dtype,
        dim_coords=dim_coords,
        category=category,
        expr=expr,
        depends_on=depends_on,
        **kwargs,
    )


class BaseModule(AbstractModule):
    # --------------------------------------------------------------------- #
    # Metadata
    # --------------------------------------------------------------------- #
    module_name: ClassVar[str] = "base"
    description: ClassVar[str] = (
        "Core hydrodynamic module with fundamental river and catchment variables"
    )

    @kernel_field
    def gravity(self) -> float:
        return self.options.value("gravity")

    @kernel_field
    def min_kinematic_slope(self) -> float:
        return self.options.value("min_kinematic_slope")

    # --------------------------------------------------------------------- #
    # Network topology
    # --------------------------------------------------------------------- #
    catchment_id: torch.Tensor = CoordinateField(
        description=(
            "Unique ID of each catchment (e.g., generated by catchment_id = np.ravel_multi_index((catchment_x, catchment_y), self.map_shape))"
        ),
        dtype="int",
        shape=("num_catchments",),
    )

    catchment_basin_id: torch.Tensor = BaseField(
        description="Basin identifier for distributed sharding",
        dtype="int",
        category="topology",
        mode="cpu",
    )

    downstream_id: torch.Tensor = ReferenceField(
        description="ID of immediate downstream catchment (points to self at river mouth)",
        dtype="int",
        shape=("num_catchments",),
        dim_coords="catchment_id",
        references="catchment_id",
    )

    # --------------------------------------------------------------------- #
    # River-channel geometry
    # --------------------------------------------------------------------- #
    river_width: torch.Tensor = BaseField(
        description="River-channel width",
        units="m",
        category="param",
        shape=("num_catchments",),
        gt=0,
    )

    river_length: torch.Tensor = BaseField(
        description="River-channel length",
        units="m",
        category="param",
        shape=("num_catchments",),
        gt=0,
    )

    river_height: torch.Tensor = BaseField(
        description="Bankfull depth of river channel",
        units="m",
        category="param",
        shape=("num_catchments",),
        gt=0,
    )

    # --------------------------------------------------------------------- #
    # Catchment properties
    # --------------------------------------------------------------------- #
    catchment_elevation: torch.Tensor = BaseField(
        description="Mean ground elevation (above mean sea level)",
        units="m",
        category="param",
    )

    catchment_area: torch.Tensor = BaseField(
        description="Surface area of catchment",
        units="m2",
        category="param",
        gt=0,
    )

    runoff: torch.Tensor = BaseField(
        description="Current external runoff forcing",
        category="forcing",
        units="m3 s-1",
        output="disabled",
        default=0,
    )

    downstream_distance: torch.Tensor = BaseField(
        description="Downstream distance",
        units="m",
        category="param",
        gt=0,
    )

    output_catchment_id: torch.Tensor = SelectionField(
        description="Catchment IDs for which output will be saved",
        dtype="int",
        shape=("num_output_catchments",),
        selects="catchment_id",
    )

    # --------------------------------------------------------------------- #
    # hydrodynamic parameters
    # --------------------------------------------------------------------- #
    river_manning: torch.Tensor = BaseField(
        description="River Manning roughness coefficient",
        units="s m-1/3",
        default=0.03,
        category="param",
        gt=0,
    )

    flood_manning: torch.Tensor = BaseField(
        description="Floodplain Manning roughness coefficient",
        units="s m-1/3",
        default=0.1,
        category="param",
        gt=0,
    )

    # --------------------------------------------------------------------- #
    # Lookup tables (dependent on num_flood_levels)
    # --------------------------------------------------------------------- #
    flood_depth_table: torch.Tensor = BaseField(
        description="Lookup table: flood depth vs. fraction of catchment area flooded",
        units="m",
        shape=("num_catchments", "num_flood_levels"),
        category="param",
        ge=0,
    )

    # --------------------------------------------------------------------- #
    # State variables (initialised to 0 where not supplied)
    # --------------------------------------------------------------------- #
    river_storage: torch.Tensor = BaseField(
        description="Current water volume in river channels, including any above bankfull depth",
        units="m3",
        default=0,
        category="init_state",
        dtype="hpfloat",
        ge=0,
    )

    flood_storage: torch.Tensor = BaseField(
        description="Current water volume stored on floodplains",
        units="m3",
        default=0,
        category="init_state",
        dtype="hpfloat",
        ge=0,
    )

    protected_storage: torch.Tensor | None = BaseField(
        description="Current water volume stored in protected areas",
        units="m3",
        default=0,
        category="init_state",
        dtype="hpfloat",
        depends_on="levee",
        ge=0,
    )

    protected_depth: torch.Tensor | None = BaseField(
        description="Current water depth on the protected side relative to river bed",
        units="m",
        default=0,
        category="init_state",
        depends_on="levee",
        ge=0,
    )

    river_depth: torch.Tensor = BaseField(
        description="Current water depth in rivers",
        units="m",
        default=0,
        category="init_state",
        ge=0,
    )

    flood_depth: torch.Tensor = BaseField(
        description="Current water depth on floodplains above river bankfull",
        units="m",
        default=0,
        category="init_state",
        ge=0,
    )

    river_outflow: torch.Tensor = BaseField(
        description="Volumetric flow rate out of rivers",
        units="m3 s-1",
        default=0,
        category="init_state",
    )

    flood_outflow: torch.Tensor = BaseField(
        description="Volumetric flow rate out of floodplains",
        units="m3 s-1",
        default=0,
        category="init_state",
    )

    river_cross_section_depth: torch.Tensor = BaseField(
        description="Effective water depth used in river-flow calculations",
        units="m",
        default=0,
        category="init_state",
        ge=0,
    )

    flood_cross_section_depth: torch.Tensor = BaseField(
        description="Effective water depth used in flood-flow calculations",
        units="m",
        default=0,
        category="init_state",
        ge=0,
    )

    flood_cross_section_area: torch.Tensor = BaseField(
        description="Cross-sectional flow area on floodplains",
        units="m2",
        default=0,
        category="init_state",
        ge=0,
    )

    flood_fraction: torch.Tensor = BaseField(
        description="Fraction of catchment area that is flooded",
        units="1",
        default=0,
        category="init_state",
        output="auto",
        ge=0,
        le=1,
    )

    # ------------------------------------------------------------------ #
    # Computed scalar dimensions
    # ------------------------------------------------------------------ #
    @computed_field(description="Total number of catchments")
    @cached_property
    def num_catchments(self) -> int:
        return self.catchment_id.shape[0]

    @computed_field(
        description="Number of catchments that will have their output saved"
    )
    @cached_property
    def num_output_catchments(self) -> int:
        return self.output_catchment_id.shape[0]

    @computed_field(
        description="Number of flood levels represented in the lookup tables"
    )
    @cached_property
    def num_flood_levels(self) -> int:
        return self.flood_depth_table.shape[-1]

    # ------------------------------------------------------------------ #
    # Computed tensor fields
    # ------------------------------------------------------------------ #
    downstream_idx = ReferenceIndexField("downstream_id")

    @computed_base_field(
        description="Total water storage per catchment",
        units="m3",
        category="state",
        dtype="hpfloat",
        output="auto",
        output_only=True,
    )
    @cached_property
    def total_storage(self) -> torch.Tensor | None:
        total = self.river_storage + self.flood_storage
        if self.protected_storage is not None:
            total = total + self.protected_storage
        return total

    # ---------------- Hidden / intermediate states ------------------- #
    @computed_base_field(
        description=(
            "Sub-step sum of the flows leaving each catchment, including flow "
            "reversed from its upstream cells; times the time step it is CaMa-Flood's "
            "outgoing volume P2STOOUT. Can not be saved, as it is a temporary state"
        ),
        units="m3 s-1",
        output="disabled",
        category="state",
        dtype="hpfloat",
    )
    @cached_property
    def outgoing_storage(self) -> torch.Tensor:
        return torch.zeros_like(
            self.river_outflow,
            dtype=self.get_expected_dtype("outgoing_storage"),
        )

    @computed_base_field(
        description="Water-surface elevation (above mean sea level)",
        units="m",
        category="virtual",
        expr="river_depth + catchment_elevation - river_height",
    )
    @cached_property
    def water_surface_elevation(self) -> torch.Tensor | None:
        return None

    @computed_base_field(
        description="Total inflow into river channels",
        units="m3 s-1",
        category="state",
        dtype="hpfloat",
    )
    @cached_property
    def river_inflow(self) -> torch.Tensor:
        return torch.zeros_like(
            self.river_outflow,
            dtype=self.get_expected_dtype("river_inflow"),
        )

    @computed_base_field(
        description="Total flooded area",
        units="m2",
        category="virtual",
        expr="flood_fraction * catchment_area",
    )
    @cached_property
    def flood_area(self) -> torch.Tensor | None:
        return None

    @computed_base_field(
        description="Total inflow to floodplains",
        units="m3 s-1",
        category="state",
        dtype="hpfloat",
    )
    @cached_property
    def flood_inflow(self) -> torch.Tensor:
        return torch.zeros_like(
            self.river_outflow,
            dtype=self.get_expected_dtype("flood_inflow"),
        )

    @computed_base_field(
        description="Total outflow from catchment (river + flood)",
        units="m3 s-1",
        category="virtual",
        expr="river_outflow + flood_outflow",
    )
    @cached_property
    def total_outflow(self) -> torch.Tensor | None:
        return None

    # ------------------------------------------------------------------ #
    # Mutable scalar buffers (1-element device tensors for CUDA Graph)
    # ------------------------------------------------------------------ #
    @computed_base_field(
        description="Current sub-step time step. Updated via.fill_() before each sub-step loop",
        units="s",
        shape=(1,),
        dim_coords=None,
        output="disabled",
        category="shared_state",
    )
    @cached_property
    def time_step(self) -> torch.Tensor:
        return torch.zeros(1, dtype=self.precision, device=self.device)

    @computed_base_field(
        description="Current outer time-step duration",
        units="s",
        shape=(1,),
        dim_coords=None,
        output="disabled",
        category="shared_state",
    )
    @cached_property
    def outer_time_step(self) -> torch.Tensor:
        return torch.zeros(1, dtype=self.precision, device=self.device)

    @computed_base_field(
        description="Current sub-step index within the time step. Updated via.fill_() before each sub-step for log kernels",
        shape=(1,),
        dim_coords=None,
        output="disabled",
        category="shared_state",
        dtype="idx",
    )
    @cached_property
    def current_step(self) -> torch.Tensor:
        return torch.zeros(1, dtype=torch.int32, device=self.device)

    # ------------------------------------------------------------------ #
    # Post-init validation
    # ------------------------------------------------------------------ #
    @model_validator(mode="after")
    def validate_parameters(self) -> Self:
        if self.num_flood_levels < 1:
            raise ValueError("flood_depth_table must contain at least one flood level")
        if self.num_flood_levels > 1:
            diffs = torch.diff(self.flood_depth_table, dim=-1)
            invalid = diffs < 0
            num_invalid = int(invalid.sum().item())
            if num_invalid:
                min_diff = diffs.min().item()
                raise ValueError(
                    "flood_depth_table must be monotonically non-decreasing; "
                    f"found {num_invalid} decreasing intervals "
                    f"(minimum diff={min_diff:.6f}). Regenerate the parameter "
                    "file with MERITMap."
                )
        return self
